#pragma once

#include "ZunBool.hpp"
#include "ZunResult.hpp"
#include "diffbuild.hpp"
#include "inttypes.hpp"

namespace th08
{
/* Spellcard::flags 位定义。 */
#define SPELLCARD_FLAG_ACTIVE_BIT 0      /* bit 0：符卡战斗进行中 */
#define SPELLCARD_FLAG_LOCKED_SHIFT 0xb  /* bit 11：锁定（不累计时间） */
#define SPELLCARD_FLAG_RESET_MASK 0x4    /* bit 2：ResetSpellcard 清除 */

// Naming scheme:
// SPELLCARD_[STAGE]_[ENEMY]_(LAST SPELL)(NUM)(DIFFICULTY)
// [] fields are mandatory
// () fields are optional
enum SpellcardNumber
{
    SPELLCARD_ST1_MBOSS_1H,
    SPELLCARD_ST1_MBOSS_1L,
    SPELLCARD_ST1_BOSS_1E,
    SPELLCARD_ST1_BOSS_1N,
    SPELLCARD_ST1_BOSS_1H,
    SPELLCARD_ST1_BOSS_1L,
    SPELLCARD_ST1_BOSS_2E,
    SPELLCARD_ST1_BOSS_2N,
    SPELLCARD_ST1_BOSS_2H,
    SPELLCARD_ST1_BOSS_2L,
    SPELLCARD_ST1_BOSS_LSN,
    SPELLCARD_ST1_BOSS_LSH,
    SPELLCARD_ST1_BOSS_LSL,

    SPELLCARD_ST2_MBOSS_1E,
    SPELLCARD_ST2_MBOSS_1N,
    SPELLCARD_ST2_MBOSS_1H,
    SPELLCARD_ST2_MBOSS_1L,
    SPELLCARD_ST2_BOSS_1E,
    SPELLCARD_ST2_BOSS_1N,
    SPELLCARD_ST2_BOSS_1H,
    SPELLCARD_ST2_BOSS_1L,
    SPELLCARD_ST2_BOSS_2E,
    SPELLCARD_ST2_BOSS_2N,
    SPELLCARD_ST2_BOSS_2H,
    SPELLCARD_ST2_BOSS_2L,
    SPELLCARD_ST2_BOSS_3E,
    SPELLCARD_ST2_BOSS_3N,
    SPELLCARD_ST2_BOSS_3H,
    SPELLCARD_ST2_BOSS_3L,
    SPELLCARD_ST2_BOSS_LSN,
    SPELLCARD_ST2_BOSS_LSH,
    SPELLCARD_ST2_BOSS_LSL,

    SPELLCARD_ST3_MBOSS_1E,
    SPELLCARD_ST3_MBOSS_1N,
    SPELLCARD_ST3_MBOSS_1H,
    SPELLCARD_ST3_MBOSS_1L,
    SPELLCARD_ST3_BOSS_1N,
    SPELLCARD_ST3_BOSS_1H,
    SPELLCARD_ST3_BOSS_1L,
    SPELLCARD_ST3_BOSS_2E,
    SPELLCARD_ST3_BOSS_2N,
    SPELLCARD_ST3_BOSS_2H,
    SPELLCARD_ST3_BOSS_2L,
    SPELLCARD_ST3_BOSS_3E,
    SPELLCARD_ST3_BOSS_3N,
    SPELLCARD_ST3_BOSS_3H,
    SPELLCARD_ST3_BOSS_3L,
    SPELLCARD_ST3_BOSS_4E,
    SPELLCARD_ST3_BOSS_4N,
    SPELLCARD_ST3_BOSS_4H,
    SPELLCARD_ST3_BOSS_4L,
    SPELLCARD_ST3_BOSS_LSN,
    SPELLCARD_ST3_BOSS_LSH,
    SPELLCARD_ST3_BOSS_LSL,

    SPELLCARD_ST4A_MBOSS_1E,
    SPELLCARD_ST4A_MBOSS_1N,
    SPELLCARD_ST4A_MBOSS_1H,
    SPELLCARD_ST4A_MBOSS_1L,
    SPELLCARD_ST4A_MBOSS_2E,
    SPELLCARD_ST4A_MBOSS_2N,
    SPELLCARD_ST4A_MBOSS_2H,
    SPELLCARD_ST4A_MBOSS_2L,
    SPELLCARD_ST4A_BOSS_1E,
    SPELLCARD_ST4A_BOSS_1N,
    SPELLCARD_ST4A_BOSS_1H,
    SPELLCARD_ST4A_BOSS_1L,
    SPELLCARD_ST4A_BOSS_2E,
    SPELLCARD_ST4A_BOSS_2N,
    SPELLCARD_ST4A_BOSS_2H,
    SPELLCARD_ST4A_BOSS_2L,
    SPELLCARD_ST4A_BOSS_3E,
    SPELLCARD_ST4A_BOSS_3N,
    SPELLCARD_ST4A_BOSS_3H,
    SPELLCARD_ST4A_BOSS_3L,
    SPELLCARD_ST4A_BOSS_LSN,
    SPELLCARD_ST4A_BOSS_LSH,
    SPELLCARD_ST4A_BOSS_LSL,

    SPELLCARD_ST4B_MBOSS_1E,
    SPELLCARD_ST4B_MBOSS_1N,
    SPELLCARD_ST4B_MBOSS_1H,
    SPELLCARD_ST4B_MBOSS_1L,
    SPELLCARD_ST4B_MBOSS_2E,
    SPELLCARD_ST4B_MBOSS_2N,
    SPELLCARD_ST4B_MBOSS_2H,
    SPELLCARD_ST4B_MBOSS_2L,
    SPELLCARD_ST4B_BOSS_1E,
    SPELLCARD_ST4B_BOSS_1N,
    SPELLCARD_ST4B_BOSS_1H,
    SPELLCARD_ST4B_BOSS_1L,
    SPELLCARD_ST4B_BOSS_2E,
    SPELLCARD_ST4B_BOSS_2N,
    SPELLCARD_ST4B_BOSS_2H,
    SPELLCARD_ST4B_BOSS_2L,
    SPELLCARD_ST4B_BOSS_3E,
    SPELLCARD_ST4B_BOSS_3N,
    SPELLCARD_ST4B_BOSS_3H,
    SPELLCARD_ST4B_BOSS_3L,
    SPELLCARD_ST4B_BOSS_LSN,
    SPELLCARD_ST4B_BOSS_LSH,
    SPELLCARD_ST4B_BOSS_LSL,

    SPELLCARD_ST5_BOSS_1E,
    SPELLCARD_ST5_BOSS_1N,
    SPELLCARD_ST5_BOSS_1H,
    SPELLCARD_ST5_BOSS_1L,
    SPELLCARD_ST5_BOSS_2E,
    SPELLCARD_ST5_BOSS_2N,
    SPELLCARD_ST5_BOSS_2H,
    SPELLCARD_ST5_BOSS_2L,
    SPELLCARD_ST5_BOSS_3E,
    SPELLCARD_ST5_BOSS_3N,
    SPELLCARD_ST5_BOSS_3H,
    SPELLCARD_ST5_BOSS_3L,
    SPELLCARD_ST5_BOSS_4E,
    SPELLCARD_ST5_BOSS_4N,
    SPELLCARD_ST5_BOSS_4H,
    SPELLCARD_ST5_BOSS_4L,
    SPELLCARD_ST5_BOSS_LSN,
    SPELLCARD_ST5_BOSS_LSH,
    SPELLCARD_ST5_BOSS_LSL,

    SPELLCARD_ST6A_MBOSS_1E,
    SPELLCARD_ST6A_MBOSS_1N,
    SPELLCARD_ST6A_MBOSS_1H,
    SPELLCARD_ST6A_MBOSS_1L,
    SPELLCARD_ST6A_BOSS_1E,
    SPELLCARD_ST6A_BOSS_1N,
    SPELLCARD_ST6A_BOSS_1H,
    SPELLCARD_ST6A_BOSS_1L,
    SPELLCARD_ST6A_BOSS_2E,
    SPELLCARD_ST6A_BOSS_2N,
    SPELLCARD_ST6A_BOSS_2H,
    SPELLCARD_ST6A_BOSS_2L,
    SPELLCARD_ST6A_BOSS_3E,
    SPELLCARD_ST6A_BOSS_3N,
    SPELLCARD_ST6A_BOSS_3H,
    SPELLCARD_ST6A_BOSS_3L,
    SPELLCARD_ST6A_BOSS_4E,
    SPELLCARD_ST6A_BOSS_4N,
    SPELLCARD_ST6A_BOSS_4H,
    SPELLCARD_ST6A_BOSS_4L,
    SPELLCARD_ST6A_BOSS_5E,
    SPELLCARD_ST6A_BOSS_5N,
    SPELLCARD_ST6A_BOSS_5H,
    SPELLCARD_ST6A_BOSS_5L,
    SPELLCARD_ST6A_BOSS_LSE,
    SPELLCARD_ST6A_BOSS_LSN,
    SPELLCARD_ST6A_BOSS_LSH,
    SPELLCARD_ST6A_BOSS_LSL,

    SPELLCARD_ST6B_MBOSS_1E,
    SPELLCARD_ST6B_MBOSS_1N,
    SPELLCARD_ST6B_MBOSS_1H,
    SPELLCARD_ST6B_MBOSS_1L,
    SPELLCARD_ST6B_BOSS_1E,
    SPELLCARD_ST6B_BOSS_1N,
    SPELLCARD_ST6B_BOSS_1H,
    SPELLCARD_ST6B_BOSS_1L,
    SPELLCARD_ST6B_BOSS_2E,
    SPELLCARD_ST6B_BOSS_2N,
    SPELLCARD_ST6B_BOSS_2H,
    SPELLCARD_ST6B_BOSS_2L,
    SPELLCARD_ST6B_BOSS_3E,
    SPELLCARD_ST6B_BOSS_3N,
    SPELLCARD_ST6B_BOSS_3H,
    SPELLCARD_ST6B_BOSS_3L,
    SPELLCARD_ST6B_BOSS_4E,
    SPELLCARD_ST6B_BOSS_4N,
    SPELLCARD_ST6B_BOSS_4H,
    SPELLCARD_ST6B_BOSS_4L,
    SPELLCARD_ST6B_BOSS_5E,
    SPELLCARD_ST6B_BOSS_5N,
    SPELLCARD_ST6B_BOSS_5H,
    SPELLCARD_ST6B_BOSS_5L,
    SPELLCARD_ST6B_BOSS_LS1E,
    SPELLCARD_ST6B_BOSS_LS1N,
    SPELLCARD_ST6B_BOSS_LS1H,
    SPELLCARD_ST6B_BOSS_LS1L,
    SPELLCARD_ST6B_BOSS_LS2E,
    SPELLCARD_ST6B_BOSS_LS2N,
    SPELLCARD_ST6B_BOSS_LS2H,
    SPELLCARD_ST6B_BOSS_LS2L,
    SPELLCARD_ST6B_BOSS_LS3E,
    SPELLCARD_ST6B_BOSS_LS3N,
    SPELLCARD_ST6B_BOSS_LS3H,
    SPELLCARD_ST6B_BOSS_LS3L,
    SPELLCARD_ST6B_BOSS_LS4E,
    SPELLCARD_ST6B_BOSS_LS4N,
    SPELLCARD_ST6B_BOSS_LS4H,
    SPELLCARD_ST6B_BOSS_LS4L,
    SPELLCARD_ST6B_BOSS_LS5E,
    SPELLCARD_ST6B_BOSS_LS5N,
    SPELLCARD_ST6B_BOSS_LS5H,
    SPELLCARD_ST6B_BOSS_LS5L,

    SPELLCARD_EX_MBOSS_1,
    SPELLCARD_EX_MBOSS_2,
    SPELLCARD_EX_MBOSS_3,
    SPELLCARD_EX_BOSS_1,
    SPELLCARD_EX_BOSS_2,
    SPELLCARD_EX_BOSS_3,
    SPELLCARD_EX_BOSS_4,
    SPELLCARD_EX_BOSS_5,
    SPELLCARD_EX_BOSS_6,
    SPELLCARD_EX_BOSS_7,
    SPELLCARD_EX_BOSS_8,
    SPELLCARD_EX_BOSS_9,
    SPELLCARD_EX_BOSS_10,
    SPELLCARD_EX_BOSS_LS,

    SPELLCARD_COUNT_IN_GAME_SPELLCARDS,
    SPELLCARD_LAST_WORD_START = SPELLCARD_COUNT_IN_GAME_SPELLCARDS,

    SPELLCARD_LW_WRIGGLE = SPELLCARD_LAST_WORD_START,
    SPELLCARD_LW_MYSTIA,
    SPELLCARD_LW_KEINE,
    SPELLCARD_LW_REISEN,
    SPELLCARD_LW_EIRIN,
    SPELLCARD_LW_KAGUYA,
    SPELLCARD_LW_MOKOU,
    SPELLCARD_LW_TEWI,
    SPELLCARD_LW_KEINEEX,
    SPELLCARD_LW_REIMU,
    SPELLCARD_LW_MARISA,
    SPELLCARD_LW_SAKUYA,
    SPELLCARD_LW_YOUMU,
    SPELLCARD_LW_ALICE,
    SPELLCARD_LW_REMILIA,
    SPELLCARD_LW_YUYUKO,
    SPELLCARD_LW_YUKARI,

    SPELLCARD_COUNT_SPELLCARDS,
    SPELLCARD_COUNT_LAST_WORD_SPELLCARDS = SPELLCARD_COUNT_SPELLCARDS - SPELLCARD_COUNT_IN_GAME_SPELLCARDS,
};

struct SpellcardDataHolder
{
    void *dataPtr;

    void FreeData();
};

struct Spellcard
{
    static i32 GetDifficultyFromSpellCard(i32 spellcardNumber);
    static ZunResult RegisterChain();
    static void CutChain();

    i32 IsSpellcardActive();
    void AddSpellcardTime(i32 arg);
    ZunResult Initialize();
    void ResetSpellcard();

    /* 跨类 thiscall 帮手 stub（内部未逆向；PDB 名对齐 reccmp-functions.csv）。
     * 原版以 this=0x4ea670 (g_EclGlobalObj 地址) 调用。 */
    i32 FUN_0042dff0();           /* 0x42dff0 */

    u32 flags;
    unknown_fields(0x4, 0xf8);
    u32 spellTime;                  // 0xfc  accumulated spell-card elapsed time (capped at maxSpellTime)
    u32 spellTimeBonus;             // 0x100  bonus counter, += arg/120 while spellTime below cap
    unknown_fields(0x104, 0x2534);
    u32 maxSpellTime;               // 0x2638  cap for spellTime
    ChainElem *calcChainElem;       // 0x263c  calc-chain elem (callback 0x418010)
    ChainElem *drawChainElem;       // 0x2640  draw-chain elem (callback 0x418030)
    unknown_fields(0x2644, 0x4);
    SpellcardDataHolder dataHolder; // 0x2648
};

DIFFABLE_EXTERN_ARRAY(i32 *, 6, g_SpellcardNumbersPerDifficulty);
DIFFABLE_EXTERN_ARRAY(i32, 6, g_SpellcardCountsPerDifficulty);
DIFFABLE_EXTERN(Spellcard, g_Spellcard);
DIFFABLE_EXTERN_ARRAY(i32, 43, g_LastSpellNumbers);
DIFFABLE_EXTERN(i32, g_LastSpellCount);
DIFFABLE_EXTERN_ARRAY(i32 *, 10, g_SpellcardNumbersPerStage)
DIFFABLE_EXTERN_ARRAY(i32, 10, g_SpellcardCountPerStage)

} /* namespace th08 */